# 12.2 try~catch로 예외 받기
* try catch 문을 통해 예외를 처리 할 수 있다
* try 블록에서 실행할 코들 적고 catch 블록에서 try 블록에서 나온 예외를 처리한다
* catch는 try 블록에서 던질 예외 객체와 형식이 일치해야 한다
